name              "apt"
maintainer        "Eberhard Wolff based on Opscode, Inc."
maintainer_email  "eberhard.wolff@gmail.com"
license           "Apache 2.0"
description       "Configures apt and apt services and an LWRP for managing apt repositories"
version           "1.2.2"
recipe            "apt", "Runs apt-get update during compile phase and sets up preseed directories"
recipe            "apt::cacher", "Set up an APT cache"
recipe            "apt::cacher-client", "Client for the apt::cacher server"
supports          "ubuntu"
