name              "java"
maintainer        "Opscode, Inc."
maintainer_email  "cookbooks@opscode.com"
license           "Apache 2.0"
description       "Installs java via openjdk."
version           "0.10.2"
depends           "apt"
supports          "ubuntu"
recipe "java", "Installs OpenJDK to provide Java"
