Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/vivid64"
  config.vm.synced_folder "../user-registration-application/target", "/target", create: true
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 5601, host: 5601
  config.vm.network "forwarded_port", guest: 9200, host: 9200

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
  
  config.vm.provision "docker" do |d|
    d.build_image "--tag=kibana /vagrant/kibana"
    d.build_image "--tag=elasticsearch /vagrant/elasticsearch"
    d.build_image "--tag=logstash /vagrant/logstash"
    d.build_image "--tag=user-registration /vagrant/user-registration"
  end    
  config.vm.provision "docker", run: "always" do |d|
    d.run "elasticsearch",
      args: "-p 9200:9200"
    d.run "kibana",
      args: "--link elasticsearch:elasticsearch -p 5601:5601"
   d.run "logstash",
      args: "--link elasticsearch:elasticsearch"
    d.run "user-registration",
      args: "-p 8080:8080 -v /target:/target --volumes-from logstash"
  end

end
